# Working With NumPy Arrays


In [3]:
#1D ARRAYS

# Creating 1D Arrays

import numpy as np

# Create a 1D array from a Python list
array = np.array([1, 2, 3, 4, 5])
print(array)

# Create a 1D array with a specified data type
array = np.array([1, 2, 3, 4, 5], dtype=float)
print(array)


# Basic Operations

import numpy as np

array = np.array([1, 2, 3, 4, 5])

# Indexing
print(array[0])
print(array[-1])

# Slicing
print(array[1:3])
print(array[1:])
print(array[:3])

# Arithmetic operations
print(array + 2)
print(array * 2)


# Statistical Functions

import numpy as np

array = np.array([1, 2, 3, 4, 5])

# Mean
print(np.mean(array))

# Median
print(np.median(array))
# Standard deviation
print(np.std(array))


# Sorting and Searching

import numpy as np

array = np.array([3, 1, 4, 2, 5])

# Sort the array
print(np.sort(array))  

# Find the index of a value
print(np.where(array == 3))  

# Array Manipulation

import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5])

# Reverse the array
print(np.flip(array))  # Output: [5 4 3 2 1]

# Shift the array
print(np.roll(array, 2))  # Output: [4 5 1 2 3]

# Repeat the array
print(np.tile(array, 2))  # Output: [1 2 3 4 5 1 2 3 4 5]

# Array Operations

import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Element-wise addition
print(array1 + array2)  # Output: [ 7  9 11 13 15]

# Element-wise multiplication
print(array1 * array2)  # Output: [ 6 14 24 36 50]

# Dot product
print(np.dot(array1, array2))  # Output: 130


# Array Statistics

import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5])

# Mean
print(np.mean(array))  # Output: 3.0

# Median
print(np.median(array))  # Output: 3.0

# Standard deviation
print(np.std(array))  # Output: 1.4142135623730951

# Variance
print(np.var(array))  # Output: 2.0


[1 2 3 4 5]
[1. 2. 3. 4. 5.]
1
5
[2 3]
[2 3 4 5]
[1 2 3]
[3 4 5 6 7]
[ 2  4  6  8 10]
3.0
3.0
1.4142135623730951
[1 2 3 4 5]
(array([0]),)
[5 4 3 2 1]
[4 5 1 2 3]
[1 2 3 4 5 1 2 3 4 5]
[ 7  9 11 13 15]
[ 6 14 24 36 50]
130
3.0
3.0
1.4142135623730951
2.0


In [1]:

import numpy as np

# Create a 1D array from a Python list

array = np.array([13,14,15, 16, 17])
print(array)
print(array//2)

[13 14 15 16 17]
[6 7 7 8 8]


In [2]:
#2D ARRAYS

# Creating 2D Arrays

import numpy as np

# Create a 2D array from a Python list
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)

# Create a 2D array with a specified shape
array = np.zeros((3, 4))
print(array)



# Basic Operations

import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

# Indexing
print(array[0, 0])  
print(array[1, 2]) 

# Slicing
print(array[0, :]) 
print(array[:, 0]) 

# Arithmetic operations
print(array + 2)

# Array Manipulation

import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose
print(array.T)


# Flatten
print(array.flatten())


# Reshape
print(array.reshape(3, 2))



# Array Operations

import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[6, 5, 4], [3, 2, 1]])

# Element-wise addition
print(array1 + array2)

# Element-wise multiplication
print(array1 * array2)

# Matrix multiplication
print(np.dot(array1, array2.T))


# Array Statistics

import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

# Mean
print(np.mean(array))  
# Median
print(np.median(array)) 

# Standard deviation
print(np.std(array)) 

# Variance
print(np.var(array))

[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1
6
[1 2 3]
[1 4]
[[3 4 5]
 [6 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[7 7 7]
 [7 7 7]]
[[ 6 10 12]
 [12 10  6]]
[[28 10]
 [73 28]]
3.5
3.5
1.707825127659933
2.9166666666666665
